# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_noted', models.DateTimeField(verbose_name='date noted')),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('Severe', 'Severe'), ('Problematic', 'Problematic'), ('Inconvenient', 'Inconvenient')], max_length=12)),
                ('description', models.CharField(max_length=100)),
                ('mechanic', models.CharField(max_length=30)),
                ('date_completed', models.DateTimeField(blank=True, null=True, verbose_name='date completed')),
                ('notes', models.TextField(blank=True)),
                ('reason', models.CharField(choices=[('Driver Write-up', 'Driver Write-up'), ('Scheduled Maintenance', 'Schedule Maintenance'), ('PM Work', 'PM Work'), ('Other', 'Other')], default='OT', max_length=21)),
                ('repair', models.CharField(blank=True, choices=[('Repaired or Tightened', 'Repaired or tightened'), ('Replaced', 'Replaced'), ('Checked, found OK', 'Checked, found OK')], max_length=21)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10)),
                ('vehicle_class', models.CharField(choices=[('Long Bus', 'Long Bus'), ('Medium Bus', 'Medium Bus'), ('Short Bus', 'Short Bus'), ('Shuttle', 'Shuttle'), ('Trolly', 'Trolly'), ('Van', 'Van'), ('Truck', 'Truck'), ('Car', 'Car')], max_length=10)),
                ('vehicle_name', models.CharField(default='default', max_length=30)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busbarn.Vehicle'),
        ),
    ]
