# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busbarn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='notes',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='notes',
            new_name='remarks',
        ),
        migrations.AlterField(
            model_name='issue',
            name='reason',
            field=models.CharField(choices=[('Driver Write-up', 'Driver Write-up'), ('PM Work', 'PM Work'), ('Other Scheduled', 'Other Scheduled')], default='OT', max_length=21),
        ),
        migrations.AlterField(
            model_name='issue',
            name='severity',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('OOS', 'OOS')], max_length=12),
        ),
    ]
