# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busbarn', '0002_auto_20171021_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vin_number',
            field=models.CharField(default=None, max_length=17, unique=True),
        ),
    ]
