# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busbarn', '0003_vehicle_vin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='mechanic',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='issue',
            name='reason',
            field=models.CharField(blank=True, choices=[('Driver Write-up', 'Driver Write-up'), ('PM Work', 'PM Work'), ('Other Scheduled', 'Other Scheduled')], max_length=21),
        ),
    ]
