# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busbarn', '0004_auto_20171028_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='reason',
            field=models.CharField(choices=[('Driver Write-up', 'Driver Write-up'), ('PM Work', 'PM Work'), ('Other Scheduled', 'Other Scheduled')], default='Other scheduled', max_length=21),
        ),
    ]
