# Generated by Django 2.1.7 on 2019-02-12 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busbarn', '0005_auto_20171028_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='mechanic_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='busbarn.Mechanic'),
        ),
    ]
