# Generated by Django 2.1.7 on 2019-02-12 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busbarn', '0008_remove_issue_mechanic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='mechanic_link',
            new_name='mechanic',
        ),
    ]
